site_name: FRC Learning Library | Team 6498
repo_url: https://github.com/DeltaDizzy/mmwiki6498NewbieLessons.git
theme: readthedocs
nav:
    - Start: 'index.md'
    - 'Components':
      - Basic Components: 'components/components.md'
    - 'Skills':
      - Essentials of Electrical: 'skills/circuits.md'
      - Stripping: 'skills/stripping.md'
      - Soldering: 'skills/soldering.md'
      - Crimping: 'skills/crimping.md'